import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {Footer} from "@/components/Footer";
import Navbar from "@/components/Navbar";
import {Hero} from "@/components/Hero";
import {Link} from "@radix-ui/react-navigation-menu";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Product",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}  >

        <Navbar></Navbar>
      {children}
      <Footer></Footer>

      </body>
    </html>
  );
}
